services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USERNAME:-dev}
    volumes:
      - ${HOME}/.ssh:/home/${USERNAME:-dev}/.ssh
      - ${HOME}/.git:/home/${USERNAME:-dev}/.git
      - .:/workspace
      - /workspace/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: npm start
    container_name: workspace
