services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USERNAME:-dev}
    volumes:
      - /home/${USER}/.ssh:/home/${USERNAME:-dev}/.ssh
      - /home/${USER}/.git:/home/${USERNAME:-dev}/.git
      - ..:/workspace
      - /workspace/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    tty: true
    container_name: workspace
